config/routes.rb
Reclutamiento::Application.routes.draw do
  resources :entrevista do
    get :autocomplete_solicitud_nombre, :on => :collection
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :solicituds do
    get :autocomplete_vacante_nombre, :on => :collection
    get :autocomplete_candidato_nombre, :on => :collection
  end
  resources :candidatos
  resources :vacantes do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :requerimientos do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :departamentos do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :areas do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :posicions
  
  
  resources :usuarios ,:only => [:show,:edit,:update,:index]
    
match '/home', :to => 'sesion#home' 
match '/login', :to => 'sesion#authenticate'
match '/logout', :to => 'sesion#destroy'
match '/aprobar_requerimiento',:to => 'requerimientos#aprobar'
match '/convertir_requerimiento',:to => 'requerimientos#convertir'
match '/convertir_vacante', :to => 'requerimientos#convertir_vacante'
match '/cancelar_requerimiento',:to => 'requerimientos#cancelar'
match '/rechazar_requerimiento',:to => 'requerimientos#rechazar'
match '/rechazar_rh_requerimiento',:to => 'requerimientos#rechazar_rh'
match '/calificar_entrevista', :to => 'entrevista#calificar'
match '/cancelar_entrevista', :to => 'entrevista#cancelar'
match '/cerrar_vacante', :to => 'vacantes#cerrar'

match '/auth/:provider/callback', :to => 'sesion#create'

 









   root :to => 'sesion#authenticate'


end

app/models/vacante.rb
# encoding: UTF-8
class Vacante < ActiveRecord::Base
  scope :no_cerradas,where("estatus != ?",'Cerrada')
  has_many :solicituds, :dependent => :destroy
	#has_many :entrevistum, :through => :solicitud
  has_many :candidatos, :through => :solicituds
  belongs_to :area
  belongs_to :requerimiento
  belongs_to :posicion  

  
  validates_presence_of :nombre, :message => "El nombre de la vacante es requerido."
  validates_presence_of :area_id, :message => "El área que solicita la vacante es requerida."
  validates_associated :area , :message => "El área que solicita debe ser un área funcional válida."
  validates_presence_of :fecha_deseada_contratacion, :message => "La fecha de contratación deseada es requerida."
  validates_presence_of :descripcion , :message => "La descripción de la vacante es requerida." 
  validates_presence_of :responsabilidades , :message => "Las responsabilidades de la vacante son requeridas."
  validates_presence_of :habilidades , :message => "Las habilidades necesarias de la vacante son requeridas."
  validates_presence_of :competencias , :message => "Las competencias necesarias de la vacante son requeridas."
  validates_presence_of :pago_minimo , :message => "El pago mínimo de la vacante es requerido."
  validates_presence_of :pago_maximo , :message => "El pago máximo de la vacante es requerido."
  validates_numericality_of :pago_minimo , :message => "El pago mínimo de la vacante debe ser un valor numérico."
  validates_numericality_of :pago_maximo , :message => "El pago máximo de la vacante debe ser un valor numérico."
  validates_presence_of :tipo , :message => "El tipo de la vacante es requerido."
  validates_presence_of :posicion_id, :message => "La posición de la vacante es requerido"
  validates_associated :posicion, :message => "La posición de la vacante debe ser una posición válida"
  
   def posicion_name
		posicion.nombre if posicion
	end
		
	def posicion_name=(nombre)
		self.posicion = Posicion.find_by_nombre(nombre) unless nombre.blank?
	end
    
end

app/controllers/vacantes_controller.rb
# encoding: UTF-8
class VacantesController < ApplicationController
  include VacantesHelper
  before_filter :authenticate
  filter_resource_access :additional_collection => :autocomplete_posicion_nombre
  autocomplete :posicion, :nombre, :full => :true
  
  def index
	@vacantes = Vacante.find(:all)

    respond_to do |format|
      format.html 
      format.xml  { render :xml => @vacantes }
	    format.js 
    end
  end

  
  def show
    @vacante = Vacante.find(params[:id])
  	@usuario_crea = Usuario.find(@vacante.created_by)
  	@usuario_actualiza = Usuario.find(@vacante.updated_by)
    
    if !@vacante.usuario_id.nil?
      @contratado =  Usuario.find(@vacante.usuario_id)
    end
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @vacante }
    end
  end
  
  def cerrar
    @vacante = Vacante.find(params[:id])    
  end
  
  def new
	  @nuevo = true
    @vacante = Vacante.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vacante }
    end
  end
  def edit
	  @nuevo = false
    @vacante = Vacante.find(params[:id])
  end
  
  
  def create
    @nuevo = true
    @vacante = Vacante.new(params[:vacante])
    @vacante.created_by = current_user.id
    @vacante.updated_by = current_user.id
    @vacante.estatus = 'Abierta'
    @vacante.fecha_inicio_reclutamiento = Date.today
    if !@vacante.posicion_id.nil?
      @vacante.area_id = @vacante.posicion.area_id
    end

    respond_to do |format|
      if @vacante.save
        format.html { redirect_to(@vacante, :notice => 'La vacante fue creada exitosamente.') }
        format.xml  { render :xml => @vacante, :status => :created, :location => @vacante }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vacante.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  def update
    @vacante = Vacante.find(params[:id])
    @vacante.updated_by = current_user.id
    
      
    respond_to do |format|
      if @vacante.update_attributes(params[:vacante])
        if @vacante.estatus == 'Cerrada'
          cambiar_estado_solicitudes(@vacante.id,@vacante.usuario_id)
        end
        format.html { redirect_to(@vacante, :notice => 'La vacante fue actualizada exitosamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vacante.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @vacante = Vacante.find(params[:id])
    @vacante.destroy

    respond_to do |format|
      format.html { redirect_to(vacantes_url) }
      format.xml  { head :ok }
    end
  end
  
 
end

app/helpers/vacantes_helper.rb
module VacantesHelper
  
  def cambiar_estado_solicitudes(vacante,candidato)
    solicitudes = Solicitud.find(:all, :conditions => ["vacante_id = ?",vacante])
    solicitudes.each do |sol|
      sol.update_attributes(:estado => 'Rechazado')
      sol.save!
    end
    if !candidato.nil?
      solicitudes2 = Solicitud.find(:all, :conditions => ["candidato_id = ? and vacante_id = ?",candidato,vacante])
      solicitudes2.each do |solicitud|
        solicitud.update_attributes(:estado => 'Contratado')
        solicitud.save!
      end
    end
  end
    
end

app/views/vacantes/_botones_forma.html.erb
  <div >
  <center>
	<% if @nuevo %>
	<%= link_to_function "Crear Vacante", "document.getElementById('forma_vacante').submit();" , :class => 'primary button' %>
	<% else %>
	<%= link_to_function "Actualizar Vacante", "document.getElementById('forma_vacante').submit();" , :class=> 'primary button' %>
	<% end %>
  <%= link_to 'Regresar', vacantes_path, :class => "primary button" %>
</center>
  </div>

app/views/vacantes/_botones_show.html.erb
<div><center>
<% if permitted_to? :edit , @vacante%>
<%= link_to 'Editar', edit_vacante_path(@vacante),  "data-icon" => "gear", "data-role" => "button", "data-inline" => "true" %> 
<% end %>
<% if permitted_to? :cerrar, @vacante%>
<% if @vacante.estatus != 'Cerrada'%>
  <%= link_to 'Cerrar Vacante', {:controller => :vacantes, :action => "cerrar", :id => @vacante},  "data-icon" => "check", "data-role" => "button", "data-inline" => "true" %>
<% end %>
<% end %>
<% if permitted_to? :destroy , @vacante%>
<%= link_to 'Eliminar', @vacante, :confirm => '¿Estás seguro?', :method => :delete,  "data-icon" => "delete", "data-role" => "button", "data-inline" => "true" %>
<% end %>
</center></div>

app/views/vacantes/_form.html.erb
<%= form_for(@vacante, :html => {:id=> "forma_vacante"}) do |f| %>

<% if @vacante.errors.any? %><br/><center>
    <div id="error_explanation">
      <h2><%= pluralize(@vacante.errors.count, "error no permite", "errores no permiten") %> registrar este vacante:</h2>
<br/>
      <ul>     
          <% @vacante.errors.each do |attribute, errors_array| %>
 
            <li><%= errors_array %></li>
           <% end %>
      </ul>
    </div></center>
  <% end %>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <% if current_user.role != 'gerente_area' %>
  <div class="field">
    <%= f.label :Área_que_solicita %><br />
    <%= f.collection_select(:area_id, Area.all, :id , :nombre, options = {:prompt => "Selecciona un área"})  %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :posicion %><br/>
    <% if params[:posicion] %>
    <%= autocomplete_field_tag 'posicion','', autocomplete_posicion_nombre_vacantes_path, :update_elements => {:id => '#vacante_posicion_id' }, :value => params[:posicion] %>
    <% else %>
    <%= autocomplete_field_tag 'posicion','', autocomplete_posicion_nombre_vacantes_path, :update_elements => {:id => '#vacante_posicion_id' } %>
    <% end %>
    <%= f.hidden_field :posicion_id, :value => params[:id] %>
  </div>
  <div class="field">
    <%= f.label :Fecha_de_contratación_deseada %><br />
    <%= f.date_select :fecha_deseada_contratacion, :order => [:day, :month, :year], :use_month_names => meses, :end_year => Time.now.year+1, :start_year => Time.now.year, :prompt => {:day => 'Día', :month => 'Mes', :year => 'Año'}  %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :responsabilidades %><br />
    <%= f.text_area :responsabilidades %>
  </div>
  <div class="field">
    <%= f.label :habilidades_necesarias %><br />
    <%= f.text_area :habilidades %>
  </div>
  <div class="field">
    <%= f.label :competencias_necesarias %><br />
    <%= f.text_area :competencias %>
  </div>  
  <div class="field">
    <%= f.label :estudios_mínimos %><br />
    <%= f.text_field :estudios %>
  </div>
  <div class="field">
    <%= f.label :pago_mínimo %><br />
    <%= f.text_field :pago_minimo %>
  </div>    
  <div class="field">
    <%= f.label :pago_máximo %><br />
    <%= f.text_field :pago_maximo %>
  </div>  
  <div class="field">
    <%= f.label :requiere_viajar %><br />
    <%= f.check_box :requiere_viajar %>
  </div>  
  <div class="field">
  <%= f.label :tipo %><br />
	<%= f.select(:tipo,["Medio Tiempo/Permanente","Tiempo Completo/Permanente","Medio Tiempo/Tempora","Tiempo Completo/Temporal","Práctica"])	%>
  </div>
<div>
    <%= f.submit "Guardar" , "data-theme" => "b",  "data-inline" => "true" %>
  </div>
  
<% end %>

app/views/vacantes/cerrar.html.erb
<div data-role="header">
  <h1>Editar Vacante</h1>
  <%= link_to 'Regresar', vacante_path(@vacante), "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<p>
  <b>Nombre:</b>
  <%= @vacante.nombre %>
</p>
<%= form_for(@vacante, :html => { :id => "forma_vacante" })  do |f| %>
<div class="field">
  <%= f.label :candidato_contratado %><br />
  <%= f.collection_select(:usuario_id, @vacante.candidatos, :id , :nombre, options = {:prompt => "Ningún candidato fue contratado"})  %>
  <%= f.hidden_field :estatus, :value => 'Cerrada' %>
  <%= f.hidden_field :fecha_cierre_reclutamiento, :value => Date.today %>
</div>
<div>
<%= f.submit "Cerrar Vacante",  "data-theme" => "b",  "data-inline" => "true"%>
</div>
<% end %>

</div>

app/views/vacantes/edit.html.erb
<div data-role="header">
  <h1>Editar Vacante</h1>
  <%= link_to 'Regresar', vacante_path(@vacante), "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/vacantes/index.html.erb
<div data-role="header">
  <h1>Lista de Vacantes</h1>
  <%= link_to 'Regresar', home_path, "data-icon" => "arrow-l" %>
  <% if permitted_to? :create, Vacante.new %>
    <%= link_to 'Agregar', new_vacante_path, "data-icon" => "plus" %>
  <% end %>
</div>

<br/>
<div data-role="content">
    <ul data-role="listview">
      <% @vacantes.each do |vacante| %>
        <li>
          <%= link_to(vacante) do %>
            <h3><%= vacante.nombre %></h3>
            <p><%= vacante.tipo %> -- <%= vacante.area.nombre %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
</div>

app/views/vacantes/index.js.erb
<%= auto_complete_result @vacantes, :nombre %>

app/views/vacantes/new.html.erb
<div data-role="header">
  <h1>Nueva Vacante</h1>
  <%= link_to 'Regresar', vacantes_path, "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/vacantes/show.html.erb
<div data-role="header">
  <h1>Detalles de la vacante</h1>
  <%= link_to 'Regresar', vacantes_path, "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<center><p id="notice"><%= notice %></p></center>

<%= render 'botones_show'%>
<br/>
<p>
  <b>Nombre:</b>
  <%= @vacante.nombre %>
</p>
<p>
  <b>Área que solicita:</b>
  <%= link_to @vacante.area.nombre, @vacante.area %>
</p>
<% if !@vacante.requerimiento.nil? %>
<p>
  <b>Requerimiento:</b>
  <%= link_to @vacante.requerimiento.nombre, @vacante.requerimiento %>
</p>
<% end %> 
<% if !@vacante.posicion.nil? %>
<p>
  <b>Posición:</b>
  <%= link_to @vacante.posicion.nombre, @vacante.posicion %>
</p>
<% end %> 
<p>
  <b>Fecha de contratación deseada:</b>
  <%= "%02d" % @vacante.fecha_deseada_contratacion.day %> /   <%=  meses[@vacante.fecha_deseada_contratacion.month-1]
 %> /   <%= @vacante.fecha_deseada_contratacion.year %>
</p>
<p>
  <b>Fecha de inicio del reclutamiento:</b>
  <%= "%02d" % @vacante.fecha_inicio_reclutamiento.day %> /   <%=  meses[@vacante.fecha_inicio_reclutamiento.month-1]
 %> /   <%= @vacante.fecha_inicio_reclutamiento.year %>
</p>
<p>
  <b>Fecha de cierre del reclutamiento:</b>
  <% if !@vacante.fecha_cierre_reclutamiento.nil? %>
  <%= "%02d" % @vacante.fecha_cierre_reclutamiento.day %> /   <%=  meses[@vacante.fecha_cierre_reclutamiento.month-1]
 %> /   <%= @vacante.fecha_cierre_reclutamiento.year %>
  <% end %>
</p>

<p>
  <b>Descripción:</b>
  <%= @vacante.descripcion %>
</p>
<p>
  <b>Responsabilidades:</b>
  <%= @vacante.responsabilidades %>
</p>

<p>
  <b>Habilidades:</b>
  <%= @vacante.habilidades %>
</p>

<p>
  <b>Competencias:</b>
  <%= @vacante.competencias %>
</p>
<p>
  <b>Estudios mínimos: </b>
  <%= @vacante.estudios %>
</p>
<p>
  <b>Pago mínimo: </b>
  <%= @vacante.pago_minimo %>
</p>
<p>
  <b>Pago máximo: </b>
  <%= @vacante.pago_maximo %>
</p>
<p>
  <b>Disponibilidad para viajar:</b>
  <% if @vacante.requiere_viajar==true %>
  Sí
  <% else %>
  No
  <% end %>
</p>
<p>
  <b>Tipo:</b>
  <%= @vacante.tipo %>
</p>
<p>
  <b>Estatus:</b>
  <%= @vacante.estatus %>
</p>

<% if @vacante.estatus == 'Cerrada'%>
<p>
<% if @vacante.usuario_id.nil? %>
  <b>Candidato Contratado:</b> No se contrató a nadie.
  <% else %>
   <b>Candidato Contratado:</b>
  <%= link_to @contratado.display_name, @contratado %>
  <% end %>
</p>  
<% end %>

<%= render 'botones_show'%>
<div data-role="collapsible" data-collapsed="true">
<h3>Información del sistema</h3>
<p>
  <b>Creado por:</b>
  <%= link_to @usuario_crea.display_name , @usuario_crea %> -  <%="%02d" %  @vacante.created_at.day %>/<%= meses[@vacante.created_at.month-1] %>/<%= @vacante.created_at.year %> - <%= "%02d" % calcularHora(@vacante.created_at.hour) %>:<%= "%02d" % @vacante.created_at.min %>:<%= "%02d" % @vacante.created_at.sec %>
</p>
<p>
  <b>Actualizado por:</b>
  <%= link_to @usuario_actualiza.display_name, @usuario_actualiza %> -  <%= "%02d" % @vacante.updated_at.day %>/<%= meses[@vacante.updated_at.month-1] %>/<%= @vacante.updated_at.year %> - <%="%02d" % calcularHora(@vacante.updated_at.hour) %>:<%= "%02d" % @vacante.updated_at.min %>:<%= "%02d" % @vacante.updated_at.sec %>
</p>

</div>
<div data-role="collapsible" data-collapsed="true">
<h3>Solicitudes asociadas a esta vacante</h3>
<center>
  <% if permitted_to? :create, Solicitud.new %>
<%= link_to 'Agregar Solicitud', new_solicitud_path(:vacante => @vacante.nombre, :id => @vacante.id), "data-icon" => "plus", "data-role" => "button", "data-inline" => "true" %>
<% end %>
</center>
<br/>
<br/>
<% if !@vacante.solicituds.empty? %>
<ul data-role="listview">
<% @vacante.solicituds.each do |solicitud| %>
  <li>
    <%= link_to(solicitud) do %>
      <h3><%= solicitud.nombre%></h3>
      <p><%= solicitud.estado %></p>
    <% end %>
  </li>
<% end %>
</ul>


<% else %>
<b><p>Ningún candidato ha aplicado a esta vacante</p></b>
<% end%>
</div>
</div>
  