config/routes.rb
Reclutamiento::Application.routes.draw do
  resources :entrevista do
    get :autocomplete_solicitud_nombre, :on => :collection
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :solicituds do
    get :autocomplete_vacante_nombre, :on => :collection
    get :autocomplete_candidato_nombre, :on => :collection
  end
  resources :candidatos
  resources :vacantes do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :requerimientos do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :departamentos do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :areas do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :posicions
  
  
  resources :usuarios ,:only => [:show,:edit,:update,:index]
    
match '/home', :to => 'sesion#home' 
match '/login', :to => 'sesion#authenticate'
match '/logout', :to => 'sesion#destroy'
match '/aprobar_requerimiento',:to => 'requerimientos#aprobar'
match '/convertir_requerimiento',:to => 'requerimientos#convertir'
match '/convertir_vacante', :to => 'requerimientos#convertir_vacante'
match '/cancelar_requerimiento',:to => 'requerimientos#cancelar'
match '/rechazar_requerimiento',:to => 'requerimientos#rechazar'
match '/rechazar_rh_requerimiento',:to => 'requerimientos#rechazar_rh'
match '/calificar_entrevista', :to => 'entrevista#calificar'
match '/cancelar_entrevista', :to => 'entrevista#cancelar'
match '/cerrar_vacante', :to => 'vacantes#cerrar'

match '/auth/:provider/callback', :to => 'sesion#create'

 









   root :to => 'sesion#authenticate'


end

app/models/solicitud.rb
# encoding: UTF-8
class Solicitud < ActiveRecord::Base
  scope :nuevas,where("estado = ?",'Nueva solicitud')
	belongs_to :vacante
	belongs_to :candidato
  has_one :area, :through => :vacante
	has_many :entrevistum, :dependent => :destroy
	validates_presence_of :vacante, :message => "El campo vacante es requerido."
  validates_presence_of :candidato, :message => "El campo candidato es requerido."
	validates_associated :vacante, :message => "Debes ingresar una vacante existente."
  #validates_associated :candidato, :message => "Debes ingresar un candidato existente."
  before_save :agrega_nombre
  
	
	def vacante_name
		vacante.nombre if vacante
	end
	
	def vacante_name=(nombre)
		self.vacante = Vacante.find_by_nombre(nombre) unless nombre.blank?
	end
	
	def candidato_name
		candidato.nombre if candidato
	end
		
	def candidato_name=(nombre)
		self.candidato = Candidato.find_by_nombre(nombre) unless nombre.blank?
	end

private 

  
  def agrega_nombre
    pos = Vacante.find(self.vacante_id)
    can = Candidato.find(self.candidato_id) 
    self.nombre = "#{pos.nombre} - #{can.nombre}"
  end
	
end

app/controllers/solicituds_controller.rb
# encoding: UTF-8
class SolicitudsController < ApplicationController
  # GET /solicituds
  # GET /solicituds.xml
 before_filter :authenticate
	filter_resource_access :additional_collection => [:autocomplete_candidato_nombre, :autocomplete_vacante_nombre]
  autocomplete :candidato, :nombre, :full => :true 
  autocomplete :vacante, :nombre, :full => :true, :scopes => :no_cerradas

  def index    
    @solicituds = Solicitud.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @solicituds }
      format.js  
    end
  end

  # GET /solicituds/1
  # GET /solicituds/1.xml
  def show
    @solicitud = Solicitud.find(params[:id])
  	@usuario_crea = Usuario.find(@solicitud.created_by)
  	@usuario_actualiza = Usuario.find(@solicitud.updated_by)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @solicitud }
    end
  end
  
  # GET /solicituds/new
  # GET /solicituds/new.xml
  def new
	@nuevo = true
  @solicitud = Solicitud.new      

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @solicitud }
      format.js
    end
  end

  # GET /solicituds/1/edit
  def edit
	@nuevo = false
    @solicitud = Solicitud.find(params[:id])
  end

  # POST /solicituds
  # POST /solicituds.xml
  def create
    @nuevo = true
    @solicitud = Solicitud.new(params[:solicitud])
    @solicitud.created_by = current_user.id
    @solicitud.updated_by = current_user.id
    @solicitud.estado = "Nueva solicitud"

    respond_to do |format|
      if @solicitud.save
        format.html { redirect_to(@solicitud, :notice => 'La solicitud fue creada exitosamente.') }
        format.xml  { render :xml => @solicitud, :status => :created, :location => @solicitud }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @solicitud.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /solicituds/1
  # PUT /solicituds/1.xml
  def update            
    @solicitud = Solicitud.find(params[:id])
    @solicitud.updated_by = current_user.id
    respond_to do |format|
      if @solicitud.update_attributes(params[:solicitud])
        format.html { redirect_to(@solicitud, :notice => 'La solicitud fue actualizada exitosamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @solicitud.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /solicituds/1
  # DELETE /solicituds/1.xml
  def destroy
    @solicitud = Solicitud.find(params[:id])
    @solicitud.destroy

    respond_to do |format|
      format.html { redirect_to(solicituds_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/solicituds/_botones_forma.html.erb
   <div>
  <center>
	<% if @nuevo %>
	<%= link_to_function "Crear Solicitud", "document.getElementById('forma_solicitud').submit();" , :class => 'primary button' %>
	<% else %>
	<%= link_to_function "Actualizar Solicitud", "document.getElementById('forma_solicitud').submit();" , :class=> 'primary button' %>
	<% end %>
  <%= link_to 'Regresar', solicituds_path, :class => "primary button" %>
</center>
  </div>

app/views/solicituds/_botones_show.html.erb
<div><center>
<% if permitted_to? :edit, @solicitud%>
<%= link_to 'Editar', edit_solicitud_path(@solicitud),"data-icon" => "gear", "data-role" => "button", "data-inline" => "true"%> 
<% end %>
<% if permitted_to? :destroy, @solicitud%>
<%= link_to 'Eliminar', @solicitud, :confirm => '¿Estás seguro?', :method => :delete, "data-icon" => "delete", "data-role" => "button", "data-inline" => "true" %></td> 
<% end %>
</center></div>

app/views/solicituds/_form.html.erb
<%= form_for(@solicitud, :html => {:id => "forma_solicitud"}) do |f| %>

   <% if @solicitud.errors.any? %><br/><center>
    <div id="error_explanation">
      <h2><%= pluralize(@solicitud.errors.count, "error no permite","errores no permiten") %> registrar esta solicitud:</h2>
	<br/>
      <ul>     
          <% @solicitud.errors.each do |attribute, errors_array| %>
 
            <li><%= errors_array %></li>
            <%if errors_array.include? "vacante"%>
              <% if permitted_to? :create , Vacante.new %>
            <%= link_to "Crea una vacante", new_vacante_path %> 
            <% end %>
            <% end %>
            <%if errors_array.include? "candidato"%>
              <% if permitted_to? :create, Candidato.new%>
           <%= link_to "Crea un candidato", new_candidato_path %>
          <% end %>
            <% end %> 
            
           <% end %>
          <br/>
        
      </ul>      
    </div> </center>
  <% end %>

  <div class="field">
    <%= f.label :candidato %><br/>
    <% if params[:candidato] %>
    <%= autocomplete_field_tag 'candidato','', autocomplete_candidato_nombre_solicituds_path, :update_elements => {:id => '#solicitud_candidato_id' }, :value => params[:candidato] %>
    <% else %>
    <%= autocomplete_field_tag 'candidato','', autocomplete_candidato_nombre_solicituds_path, :update_elements => {:id => '#solicitud_candidato_id' } %>
    <% end %>
    <%= f.hidden_field :candidato_id, :value => params[:id] %>
  </div>
  <div class="field">
    <%= f.label :vacante %><br/>
    <% if params[:vacante] %>
    <%= autocomplete_field_tag 'vacante','', autocomplete_vacante_nombre_solicituds_path, :update_elements => {:id => '#solicitud_vacante_id' }, :value => params[:vacante] %>
    <% else %>
    <%= autocomplete_field_tag 'vacante','', autocomplete_vacante_nombre_solicituds_path, :update_elements => {:id => '#solicitud_vacante_id' } %>
    <% end %>
    <%= f.hidden_field :vacante_id, :value => params[:id] %>
  </div>    
  <div>
  <%= f.submit "Guardar" , "data-theme" => "b",  "data-inline" => "true"%>
  </div> 
<% end %>

app/views/solicituds/edit.html.erb
<div data-role="header">
  <h1>Editar Solicitud</h1>
  <%= link_to 'Regresar', solicitud_path(@solicitud), "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/solicituds/index.html.erb
<div data-role="header">
  <h1>Lista de Solicitudes</h1>
  <%= link_to 'Regresar', home_path, "data-icon" => "arrow-l" %>
  <% if permitted_to? :create, Solicitud.new %>
    <%= link_to 'Agregar', new_solicitud_path, "data-icon" => "plus" %>
  <% end %>
</div>
<br/>
<div data-role="content">
<ul data-role="listview">
<% @solicituds.each do |solicitud| %>
  <li>
    <%= link_to(solicitud) do %>
    <h3><%= solicitud.nombre %></h3>
    <p><%= solicitud.estado %></p>
    <% end %>  
  </li>
<% end %>
</ul>

</div>

app/views/solicituds/index.js.erb
<%= auto_complete_result @solicituds, :nombre %>

app/views/solicituds/new.html.erb
<div data-role="header">
  <h1>Nueva Solicitud</h1>
  <%= link_to 'Regresar', solicituds_path, "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/solicituds/show.html.erb
<div data-role="header">
  <h1>Detalles de la solicitud</h1>
  <%= link_to 'Regresar', solicituds_path, "data-icon" => "arrow-l" %>
</div>
<center><p id="notice"><%= notice %></p></center>

<%= render 'botones_show'%>
<br/>
<p>
  <b>Candidato:</b>
  <%= link_to @solicitud.candidato.nombre, @solicitud.candidato %>
</p>

<p>
  <b>Vacante:</b>
  <%= link_to @solicitud.vacante.nombre, @solicitud.vacante %>
</p>

<p>
  <b>Estatus:</b>
  <%= @solicitud.estado %>
</p>

<br/>
<div data-role="collapsible" data-collapsed="true">
<h5>Información del sistema</h5>
<p>
  <b>Creado por:</b>
  <%= link_to @usuario_crea.display_name ,@usuario_crea%> -  <%= "%02d" % @solicitud.created_at.day %>/<%= meses[@solicitud.created_at.month-1] %>/<%= @solicitud.created_at.year %> - <%= "%02d" % calcularHora(@solicitud.created_at.hour) %>:<%= "%02d" % @solicitud.created_at.min %>:<%= "%02d" % @solicitud.created_at.sec %>
</p>
<p>
  <b>Actualizado por:</b>
  <%= link_to @usuario_actualiza.display_name, @usuario_actualiza %> -  <%= "%02d" % @solicitud.updated_at.day %>/<%= meses[@solicitud.updated_at.month-1] %>/<%= @solicitud.updated_at.year %> - <%= "%02d" % calcularHora(@solicitud.updated_at.hour) %>:<%= "%02d" % @solicitud.updated_at.min %>:<%= "%02d" % @solicitud.updated_at.sec %>
</p>
</div>
<div data-role="collapsible" data-collapsed="true">
<h5>Entrevistas agendadas para esta solicitud</h5>
<center>
<% if permitted_to? :create, Entrevistum.new %>
<%= link_to 'Agregar Entrevista', new_entrevistum_path(:solicitud => @solicitud.nombre, :id => @solicitud.id), "data-role" => "button", "data-icon" => "plus", "data-inline" => "true" %>
<% end %></center>

<ul data-role="listview">
<% @solicitud.entrevistum.each do |entrevistum| %>
  <li>
    <%= link_to(entrevistum) do %> 	
    <h3><%= "%02d" %entrevistum.fecha.day %>/<%= meses[entrevistum.fecha.month] %>/<%= entrevistum.fecha.year%>-<%= "%02d" % calcularHora(entrevistum.fecha.hour) %>:<%= "%02d" % entrevistum.fecha.min%></h3>
    <p>Entrevistador : <%= entrevistum.usuario.display_name %></p>
    <% end %> 
  </li>
<% end %>  

</ul>