config/routes.rb
Reclutamiento::Application.routes.draw do
  resources :entrevista do
    get :autocomplete_solicitud_nombre, :on => :collection
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :solicituds do
    get :autocomplete_vacante_nombre, :on => :collection
    get :autocomplete_candidato_nombre, :on => :collection
  end
  resources :candidatos
  resources :vacantes do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :requerimientos do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :departamentos do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :areas do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :posicions
  
  
  resources :usuarios ,:only => [:show,:edit,:update,:index]
    
match '/home', :to => 'sesion#home' 
match '/login', :to => 'sesion#authenticate'
match '/logout', :to => 'sesion#destroy'
match '/aprobar_requerimiento',:to => 'requerimientos#aprobar'
match '/convertir_requerimiento',:to => 'requerimientos#convertir'
match '/convertir_vacante', :to => 'requerimientos#convertir_vacante'
match '/cancelar_requerimiento',:to => 'requerimientos#cancelar'
match '/rechazar_requerimiento',:to => 'requerimientos#rechazar'
match '/rechazar_rh_requerimiento',:to => 'requerimientos#rechazar_rh'
match '/calificar_entrevista', :to => 'entrevista#calificar'
match '/cancelar_entrevista', :to => 'entrevista#cancelar'
match '/cerrar_vacante', :to => 'vacantes#cerrar'

match '/auth/:provider/callback', :to => 'sesion#create'

 









   root :to => 'sesion#authenticate'


end

app/models/posicion.rb
# encoding: UTF-8
class Posicion < ActiveRecord::Base  
  has_many :vacantes
  has_many :requerimientos
  belongs_to :area
  validates_presence_of :nombre, :message => "El nombre de la posición es requerido."
  validates_presence_of :area, :message => "El nombre de la área es requerido."
  validates_associated :area, :message => "Debes ingresar una área existente."
  
end

app/controllers/posicions_controller.rb
# encoding: UTF-8
class PosicionsController < ApplicationController
  
    before_filter :authenticate
    filter_resource_access 
  
  def index
    @posicions = Posicion.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posicions }
      format.js
    end
  end

  def show
  @posicion = Posicion.find(params[:id])
  @usuario_crea = Usuario.find(@posicion.created_by)
  @usuario_actualiza = Usuario.find(@posicion.updated_by)
  
  
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @posicion }
    end
  end

  
  def new
	@nuevo = true
  @posicion = Posicion.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @posicion }
    end
  end

  # GET /entrevista/1/edit
  def edit
	@nuevo = false
    @posicion = Posicion.find(params[:id])
  end
    
  
  def create
    @nuevo = true
    @posicion= Posicion.new(params[:posicion])    
    @posicion.created_by = current_user.id
    @posicion.updated_by = current_user.id
    

    respond_to do |format|
      if @posicion.save
        format.html { redirect_to(@posicion, :notice => 'La posición fue creada exitosamente.') }
        format.xml  { render :xml => @posicion, :status => :created, :location => @posicion }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @posicion.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  def update
    @posicion = Posicion.find(params[:id])
        @posicion.updated_by = current_user.id
                

    respond_to do |format|
      if @posicion.update_attributes(params[:posicion])
        format.html { redirect_to(@posicion, :notice => 'La posición fue actualizada exitosamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @posicion.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @posicion= Posicion.find(params[:id])
    @posicion.destroy

    respond_to do |format|
      format.html { redirect_to(entrevista_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/posicions_helper.rb
module PosicionsHelper
end

app/views/posicions/_botones_forma.html.erb
  <div>
  <center>
	<% if @nuevo %>
	<%= link_to_function "Crear Posición", "document.getElementById('forma_posicion').submit();" , :class => 'primary button' %>
	<% else %>
	<%= link_to_function "Actualizar Posición", "document.getElementById('forma_posicion').submit();" , :class=> 'primary button' %>
	<% end %>
  <%= link_to 'Regresar', posicions_path, :class => "primary button" %>
</center>
</div>

app/views/posicions/_botones_show.html.erb
<div>
<center>
<% if permitted_to? :edit, @posicion %>
<%= link_to 'Editar', edit_posicion_path(@posicion), "data-icon" => "gear", "data-role" => "button", "data-inline" => "true"%> 
<% end %>
<% if permitted_to? :destroy, @posicion %>
<%= link_to 'Eliminar', @posicion, :confirm => '¿Estas seguro?', :method => :delete, "data-icon" => "delete", "data-role" => "button", "data-inline" => "true" %></td> 
<% end %>
</center></div>

app/views/posicions/_form.html.erb
<%= form_for(@posicion,  :html => { :multipart => true , :id => "forma_posicion"}) do |f| %>

<br/>
  <% if @posicion.errors.any? %>
    <center><div id="error_explanation">
      <h2><%= pluralize(@posicion.errors.count, "error no permite","errores no permiten") %> registrar a esta posición:</h2>
	<br/>
      <ul>     
          <% @posicion.errors.each do |attribute, errors_array| %>
 
            <li><%= errors_array %></li>
           <% end %>
      </ul>
    </div></center>
  <% end %>
  <br/>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :Área%><br />
    <%= f.collection_select(:area_id, Area.all, :id , :nombre, options = {:prompt => "Selecciona un área"})  %>
  </div>
  <div>
  <%= f.submit "Guardar" , "data-theme" => "b",  "data-inline" => "true"%>
  </div>
<% end %>

app/views/posicions/edit.html.erb
<div data-role="header">
  <h1>Editar Posición</h1>
  <%= link_to 'Regresar', posicion_path(@posicion), "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/posicions/index.html.erb
<div data-role="header">
  <h1>Lista de Posiciones</h1>
  <%= link_to 'Regresar', home_path, "data-icon" => "arrow-l" %>
  <% if permitted_to? :create, Posicion.new %>
    <%= link_to 'Agregar', new_posicion_path, "data-icon" => "plus" %>
  <% end %>
</div>
<br/>
<div data-role="content">
  
  <ul data-role="listview">
    <% @posicions.each do |pos| %>
      <li>
      <%= link_to(pos) do %>
        <h3><%= pos.nombre %></h3>
        <p><%= pos.area.nombre%></p>
      <% end %>
      </li>
    <% end %>
  </ul>

app/views/posicions/index.js.erb
<%= auto_complete_result(@posicions, :nombre) %>

app/views/posicions/new.html.erb
<div data-role="header">
  <h1>Nueva Posición</h1>
  <%= link_to 'Regresar', posicions_path, "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<%= render 'form' %>
</div>

app/views/posicions/show.html.erb
<div data-role="header">
  <h1>Detalles de la posición</h1>
  <%= link_to 'Regresar', posicions_path, "data-icon" => "arrow-l" %>
</div>
<div data-role="content">
<center><p id="notice"><%= notice %></p></center>
<h3>Detalles de la posición</h3>
<%= render 'botones_show'%>
<br/>
<p>
  <b>Nombre:</b>
  <%= @posicion.nombre %>
</p>

<p>
  <b>Área:</b>
  <%= link_to @posicion.area.nombre, @posicion.area %>
</p>
<br/>
<div data-role="collapsible" data-collapsed="true">
<h5>Información del sistema</h5>
<p>
  <b>Creado por:</b>
  <%= link_to @usuario_crea.display_name, @usuario_crea %> -  <%= "%02d" % @posicion.created_at.day %>/<%= meses[@posicion.created_at.month-1] %>/<%= @posicion.created_at.year %> - <%= "%02d" % calcularHora(@posicion.created_at.hour) %>:<%= "%02d" % @posicion.created_at.min %>:<%= "%02d" % @posicion.created_at.sec %>
</p>
<p>
  <b>Actualizado por:</b>
  <%= link_to @usuario_actualiza.display_name , @usuario_actualiza %> -  <%= "%02d" % @posicion.updated_at.day %>/<%= meses[@posicion.updated_at.month-1] %>/<%= @posicion.updated_at.year %> - <%= "%02d" % calcularHora(@posicion.updated_at.hour) %>:<%= "%02d" % @posicion.updated_at.min %>:<%= "%02d" % @posicion.updated_at.sec %>
</p>
</div>
<div data-role="collapsible" data-collapsed="true">
<h5>Vacantes relacionadas a esta posición</h5>
<center>
  <% if permitted_to? :create, Vacante.new %>
<%= link_to 'Agregar Vacante', new_vacante_path(:posicion => @posicion.nombre, :id => @posicion.id), "data-icon" => "plus", "data-role" => "button", "data-inline" => "true" %>
<% end %>
</center>
<br/>

<% if !@posicion.vacantes.empty? %>

<ul data-role="listview">
<% @posicion.vacantes.each do |vacante| %>
  <li>
    <%= link_to(vacante) do %>
      <h3><%= vacante.nombre %></h3>
        <p><%= vacante.tipo %></p>
    <% end %>
  </li>
<% end %>
</ul>

<% else %>
<p>Esta posición no tiene ninguna vacante relacionada todavía</p>
<% end%>
<br/>
</div>
<div data-role="collapsible" data-collapsed="true">
<h5>Requerimientos relacionados a esta posición</h5>
<center>
  <% if permitted_to? :create, Requerimiento.new %>
<%= link_to 'Agregar Requerimiento', new_requerimiento_path(:posicion => @posicion.nombre, :id => @posicion.id), "data-icon" => "plus", "data-role" => "button", "data-inline" => "true" %>
<% end %>
</center>
<br/>

<% if !@posicion.requerimientos.empty? %>

<ul data-role="listview">
<% @posicion.requerimientos.each do |requerimiento| %>
  <li>
    <%= link_to(requerimiento) do %></td>
      <h3><%= requerimiento.nombre %></h3>
      <p><%= requerimiento.tipo %></p>
    <% end %>
  </li>
<% end %>

</ul>

<% else %>
<p>Esta posición no tiene ningun requerimiento relacionado todavía</p>
<% end%>
</div>
</div>