config/routes.rb
Reclutamiento::Application.routes.draw do
  resources :entrevista do
    get :autocomplete_solicitud_nombre, :on => :collection
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :solicituds do
    get :autocomplete_vacante_nombre, :on => :collection
    get :autocomplete_candidato_nombre, :on => :collection
  end
  resources :candidatos
  resources :vacantes do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :requerimientos do
    get :autocomplete_posicion_nombre, :on => :collection
  end
  resources :departamentos do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :areas do
    get :autocomplete_usuario_display_name, :on => :collection
  end
  resources :posicions
  
  
  resources :usuarios ,:only => [:show,:edit,:update,:index]
    
match '/home', :to => 'sesion#home' 
match '/login', :to => 'sesion#authenticate'
match '/logout', :to => 'sesion#destroy'
match '/aprobar_requerimiento',:to => 'requerimientos#aprobar'
match '/convertir_requerimiento',:to => 'requerimientos#convertir'
match '/convertir_vacante', :to => 'requerimientos#convertir_vacante'
match '/cancelar_requerimiento',:to => 'requerimientos#cancelar'
match '/rechazar_requerimiento',:to => 'requerimientos#rechazar'
match '/rechazar_rh_requerimiento',:to => 'requerimientos#rechazar_rh'
match '/calificar_entrevista', :to => 'entrevista#calificar'
match '/cancelar_entrevista', :to => 'entrevista#cancelar'
match '/cerrar_vacante', :to => 'vacantes#cerrar'

match '/auth/:provider/callback', :to => 'sesion#create'

 









   root :to => 'sesion#authenticate'


end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
	Copyright SOLCOM Internacional
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

	<% if signed_in? %>

<nav class="round">

<%= tabs_for do |tab| %>
  <% tab.create_ajax(usuario_path(current_user.id), 'Mi perfil') do %>
	<% end %>
  <% tab.create_ajax(usuarios_path, 'Empleados') do %>
	<% end %>
  <% tab.create_ajax(requerimientos_path, 'Requerimientos') do %>
	<% end %>
  	<% tab.create_ajax(vacantes_path, 'Vacantes') do %>
	<% end %>
    	<% tab.create_ajax(posicions_path, 'Posiciones') do %>
	<% end %>
  	<% tab.create_ajax(candidatos_path, 'Candidatos') do %>
	<% end %>
    	<% tab.create_ajax(solicituds_path, 'Solicitudes') do %>
	<% end %>
    	<% tab.create_ajax(entrevista_path, 'Entrevistas') do %>
	<% end %>
      	<% tab.create_ajax(areas_path, 'Areas') do %>
  <% end %>
    	<% tab.create_ajax(logout_path, 'Logout') do %>
	<% end %>

<% end %>

	<% end %>
  </nav>
  <br/>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  <title><%= @title %></title>
  <%= javascript_include_tag ['jquery-1.6.1.min','jquery-ui-1.8.14.custom.min','jquery.ui.core.min',
    'jquery.ui.position.min','jquery.ui.widget.min','jquery.ui.autocomplete.min','autocomplete-rails',
    'rails','application']%>

  <%= stylesheet_link_tag "http://code.jquery.com/mobile/latest/jquery.mobile.min.css", :media => 'screen' %>

  <%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.14.custom', :media => 'screen' %>  
  <script src="http://code.jquery.com/mobile/latest/jquery.mobile.min.js"></script>

  <%= csrf_meta_tag %>
    
</head>
<body>
      <div data-role="page">
     <!-- <div class="container">
     <%= render 'layouts/header' %> 
    
		<section class="round"> -->
			<%= yield %>
		<!--  </section>
  </div>
		<%= render 'layouts/footer' %> 
    </div> -->
  </div>
</body>
</html>